site_name: gravity ai
site_url: https://gravity-ai.com
site_description: Documentation for Gravity AI
copyright: "&#169; 2020-2022 Gravity AI"
nav:
  - Home: index.md
  - Using Containers:
      - Purchasing a Model: purchasing.md
      - Integrating Production Containers: using-containers.md
      - License Keys: license-keys.md
      - Mapping File Format: mapping-file.md
      - Sharing Data Amongst Containers: sharing-data.md
  - Creating a New Project:
      - Getting Started: create-project.md
      - Build Configuration File: build-config.md
      - Structured Data Schema: schema-paths.md
      - Uploading an R Project: upload-r-project.md
  - Tutorials: tutorials.md
plugins:
  - macros
extra:
  supported:
    debian:
      version_name: buster slim
    r:
      version_number: 0.9.3
  expiration:
    license:
      duration_in_days: 30
  analytics:
    gtag: UA-145378630-1
theme: 
  name: readthedocs
  custom_dir: overrides/
