site_name: gravity ai
site_url: https://gravity-ai.com
site_description: Documentation for Gravity AI
copyright: "&#169; 2020-2022 Gravity AI"
nav:
  - gravityAI: 
    - gravityAI: gravityAI.md
    - Bounty Request Approval Process: bountyRequestApprovalProcess.md
    - Bounty Fulfillment Process: bountyFulfillmentProcess.md
    - Model Approval Process: modelApprovalProcess.md
    - Purchasing a Model: purchasing.md
  - Build Process: 
    - Build Configuration: buildProcess.md
    - Building Models: buildingModels.md
    - Input Output Handling: inputOutputHandling.md
    - Schemas: schema.md
    - Troubleshooting: troubleshootingModels.md
  - Test Process: 
    - Build testing: buildTesting.md
  - Using Containers:
      - Integrating Production Containers: using-containers.md
      - License Keys: license-keys.md
      - Mapping File Format: mapping-file.md
      - Sharing Data Amongst Containers: sharing-data.md
      - Container API: container-api.md
  - Creating a New Project:
      - Getting Started: create-project.md
      - Model Documentation: documentation-examples.md
      - Uploading an R Project: upload-r-project.md
      - Tutorials: tutorials.md
plugins:
  - macros
  - mkdocs-video
extra:
  supported:
    debian:
      version_name: buster slim
    r:
      version_number: 0.9.3
  expiration:
    license:
      duration_in_days: 30
  analytics:
    gtag: G-292832164
theme: 
  name: readthedocs
  custom_dir: overrides/
markdown_extensions:
  - tables
  - pymdownx.highlight
  - codehilite:
      guess_lang: true
      linenums: true
  - pymdownx.highlight:
      auto_title: true
      anchor_linenums: true
      use_pygments: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
